Install/Uninstall support for RPM as well as Debian. No Mac OS X yet

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -8,15 +8,14 @@
 # You should probably be running a more recent version of apt
 # On these early versions, install with the following:
 #
-# sudo dpkg -i "${DEB}"
+# sudo dpkg -i "${PKG}"
 # sudo apt-get install -f
 
-SRC_NAME="gdrive"
-PKG_NAMES="gdrive"
-APT_NAMES="gdrive"
+SRC_NAME="DriveCommandLine"
+PKG_NAMES="DriveCommandLine"
+APT_NAMES="drivecommandline"
 SRC="${HOME}/src"
 
-PKG_INSTALLED=
 PKG_AVAILABLE=
 PKG_SELECTED=
 
@@ -36,59 +35,12 @@ get_available_packages() {
     [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}" ] || {
       for pkg in ${pkgs}
       do
-        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}.${SUF}//"` 
+        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}-${PKG_REL}.${SUF}//"` 
         PKG_AVAILABLE="${PKG_AVAILABLE} ${pkgname}"
       done
     }
   done
   PKG_AVAILABLE=`echo $PKG_AVAILABLE | sed -e "s/^ //"`
-}
-
-get_installed_packages() {
-  for pkg in ${APT_NAMES}
-  do
-    dpkg -s ${pkg} | grep Status: | grep 'ok installed' > /dev/null && {
-      case "${pkg}" in
-        "gdrive")
-            PKG_INSTALLED="${PKG_INSTALLED} gdrive"
-            ;;
-       esac
-    }
-  done
-  PKG_INSTALLED=`echo $PKG_INSTALLED | sed -e "s/^ //"`
-}
-
-check_package_names() {
-  for nam in ${PKG_NAMES}
-  do
-    echo "${PKG_NAMES}" | grep ${nam} > /dev/null || {
-      echo "${nam} is not a valid package name. Skipping installation of ${nam}"
-      PKG_NAMES=`echo "${PKG_NAMES}" | sed -e "s/${nam}//"`
-    }
-  done
-  echo "${PKG_NAMES}" | grep gdrive > /dev/null && {
-    # Make sure gdrive is installed first
-    pkg_names_tmp=`echo "${PKG_NAMES}" | sed -e "s/gdrive//"`
-    PKG_NAMES="gdrive ${pkg_names_tmp}"
-  }
-}
-
-debian=
-have_apt=`type -p apt`
-have_dpkg=`type -p dpkg`
-have_rpm=`type -p rpm`
-have_yum=`type -p yum`
-[ -f /etc/os-release ] && . /etc/os-release
-[ "${ID_LIKE}" == "debian" ] && debian=1
-[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
-
-SUF=deb
-[ "${debian}" ] || SUF=rpm
-
-get_available_packages
-[ "$PKG_AVAILABLE}" ] || {
-  echo "No packages for version ${PKG_VER}-${PKG_REL} are currently available. Exiting."
-  exit 1
 }
 
 install_selected() {
@@ -114,82 +66,125 @@ install_selected() {
   PKG_SELECTED=`echo $PKG_SELECTED | sed -e "s/^ //"`
 }
 
-[ "$1" ] && {
-  # If invoked with -i argument, present a menu of options to select from
-  if [ "$1" == "-i" ]
+plat=`uname -s`
+if [ "$plat" == "Darwin" ]
+then
+  if [ -x ./macInstall ]
   then
-    shift
-    PKG_NAMES="$*"
-    check_package_names
-    get_installed_packages
-    [ "${PKG_INSTALLED}" ] && {
-      echo "Currently installed gdrive packages:"
-      echo ""
-      for instpkg in ${PKG_INSTALLED}
-      do
-        echo "$instpkg"
-      done
-      echo ""
-    }
-    [ "${PKG_AVAILABLE}" ] && {
-      echo "Currently available gdrive packages:"
-      echo ""
-      for avaipkg in ${PKG_AVAILABLE}
-      do
-        echo "$avaipkg"
-      done
-      echo ""
-    }
-    while true
-    do
-      PS3="${BOLD}Please enter your desire (numeric or text): ${NORMAL}"
-      options=("Install All" "Install Selected" "Quit")
-      select opt in "${options[@]}"
-      do
-        case "$opt,$REPLY" in
-            "Install All",*|*,"Install All")
-                PKG_NAMES="${PKG_AVAILABLE}"
-                break 2
-                ;;
-            "Install Selected",*|*,"Install Selected")
-                install_selected
-                PKG_NAMES="${PKG_SELECTED}"
-                break 2
-                ;;
-            "Quit",*|*,"Quit"|"quit",*|*,"quit")
-                printf "\nExiting\n"
-                exit 0
-                ;;
-        esac
-      done
-    done
+    ./macInstall
   else
-    PKG_NAMES="$*"
+    echo "Mac OS X installation coming soon"
   fi
-  check_package_names
-}
+else
+  debian=
+  have_apt=`type -p apt`
+  have_dpkg=`type -p dpkg`
+  have_rpm=`type -p rpm`
+  have_yum=`type -p yum`
+  [ -f /etc/os-release ] && . /etc/os-release
+  [ "${ID_LIKE}" == "debian" ] && debian=1
+  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
 
-[ "${PKG_NAMES}" ] || {
-  echo "No valid Package names specified. Exiting."
-  exit 1
-}
+  SUF=deb
+  [ "${debian}" ] || SUF=rpm
 
-for PKG_NAME in ${PKG_NAMES}
-do
-  DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
-  [ -f "${DEB}" ] || {
-    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF} not found."
-    for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
-    do
-      [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
-        echo "Found existing packages:"
-        echo "${pkgs}"
-      }
-    done
-    echo ""
-    continue
+  get_available_packages
+
+  [ "$PKG_AVAILABLE}" ] || {
+    echo "No packages for version ${PKG_VER} are currently available. Exiting."
+    exit 1
   }
 
-  echo "Installing ${DEB}"
-  sudo apt install "${DEB}"
-done
+  [ "$1" ] && {
+    # If invoked with -i argument, present a menu of options to select from
+    if [ "$1" == "-i" ]
+    then
+      shift
+      PKG_NAMES="$*"
+      [ "${PKG_AVAILABLE}" ] && {
+        echo "Currently available DriveCommandLine packages:"
+        echo ""
+        for avaipkg in ${PKG_AVAILABLE}
+        do
+          echo "$avaipkg"
+        done
+        echo ""
+      }
+      while true
+      do
+        PS3="${BOLD}Please enter your desire (numeric or text): ${NORMAL}"
+        options=("Install All" "Install Selected" "Quit")
+        select opt in "${options[@]}"
+        do
+          case "$opt,$REPLY" in
+              "Install All",*|*,"Install All")
+                  PKG_NAMES="${PKG_AVAILABLE}"
+                  break 2
+                  ;;
+              "Install Selected",*|*,"Install Selected")
+                  install_selected
+                  PKG_NAMES="${PKG_SELECTED}"
+                  break 2
+                  ;;
+              "Quit",*|*,"Quit"|"quit",*|*,"quit")
+                  printf "\nExiting\n"
+                  exit 0
+                  ;;
+          esac
+        done
+      done
+    else
+      PKG_NAMES="$*"
+    fi
+  }
+
+  [ "${PKG_NAMES}" ] || {
+    echo "No valid Package names specified. Exiting."
+    exit 1
+  }
+
+  for PKG_NAME in ${PKG_NAMES}
+  do
+    PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
+    [ -f "${PKG}" ] || {
+      echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF} not found."
+      for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
+      do
+        [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
+          echo "Found existing packages:"
+          echo "${pkgs}"
+        }
+      done
+      echo ""
+      continue
+    }
+
+    echo "Installing ${PKG}"
+    if [ "${debian}" ]
+    then
+      if [ "${have_apt}" ]
+      then
+        sudo apt install "${PKG}"
+      else
+        if [ "${have_dpkg}" ]
+        then
+          sudo dpkg -i "${PKG}"
+        else
+          echo "Cannot locate either apt or dpkg to install. Skipping."
+        fi
+      fi
+    else
+      if [ "${have_yum}" ]
+      then
+        sudo yum localinstall "${PKG}"
+      else
+        if [ "${have_rpm}" ]
+        then
+          sudo rpm -i "${PKG}"
+        else
+          echo "Cannot locate either yum or rpm to install. Skipping."
+        fi
+      fi
+    fi
+  done
+fi
